# Generated by Django 4.0.3 on 2022-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0002_alter_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('CSIT', 'csit'), ('CSE', 'cse'), ('AIDS', 'aids')], max_length=100),
        ),
    ]
