# Generated by Django 4.0.3 on 2022-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0003_alter_employee_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('CSE', 'cse'), ('AIDS', 'aids'), ('CSIT', 'csit')], max_length=100),
        ),
    ]
